export const flashSales = [
  {
    id: "1",
    name: "Product 1",
    stock: 8,
    reviews: { stars: 4, number: 55 },
    price: 444,
    originalPrice: 555,
    image: "/assets/p1.webp",
    itemCount: 1,
  },
  {
    id: "2",
    name: "Product 2",
    stock: 8,
    reviews: { stars: 4, number: 55 },
    price: 444,
    originalPrice: 555,
    image: "/assets/p2.webp",
    itemCount: 1,
  },
  {
    id: "3",
    name: "Product 3",
    stock: 12,
    reviews: { stars: 5, number: 89 },
    price: 555,
    originalPrice: 699,
    image: "/assets/p3.webp",
    itemCount: 1,
  },
  {
    id: "4",
    name: "Product 4",
    stock: 6,
    reviews: { stars: 3, number: 42 },
    price: 299,
    originalPrice: 349,
    image: "/assets/p4.webp",
    itemCount: 1,
  },
  {
    id: "5",
    name: "Product 5",
    stock: 15,
    reviews: { stars: 4, number: 102 },
    price: 199,
    originalPrice: 250,
    image: "/assets/p5.webp",
    itemCount: 1,
  },
  {
    id: "6",
    name: "Product 6",
    stock: 20,
    reviews: { stars: 3, number: 77 },
    price: 129,
    originalPrice: 179,
    image: "/assets/p6.webp",
    itemCount: 1,
  },
  {
    id: "7",
    name: "Product 7",
    stock: 10,
    reviews: { stars: 5, number: 120 },
    price: 649,
    originalPrice: 799,
    image: "/assets/p7.webp",
    itemCount: 1,
  },
  {
    id: "8",
    name: "Product 8",
    stock: 4,
    reviews: { stars: 2, number: 35 },
    price: 89,
    originalPrice: 120,
    image: "/assets/p8.webp",
    itemCount: 1,
  },
  {
    id: "9",
    name: "Product 9",
    stock: 18,
    reviews: { stars: 4, number: 67 },
    price: 379,
    originalPrice: 450,
    image: "/assets/p9.webp",
    itemCount: 1,
  },
  {
    id: "10",
    name: "Product 10",
    stock: 5,
    reviews: { stars: 3, number: 55 },
    price: 299,
    originalPrice: 340,
    image: "/assets/p10.webp",
    itemCount: 1,
  },
];

export const bestSelling = [
  {
    id: "1",
    name: "Product 1",
    stock: 8,
    reviews: { stars: 4, number: 55 },
    price: 444,
    originalPrice: 555,
    image: "/assets/p1.webp",
    itemCount: 1,
  },
  {
    id: "3",
    name: "Product 3",
    stock: 12,
    reviews: { stars: 5, number: 89 },
    price: 555,
    originalPrice: 699,
    image: "/assets/p3.webp",
    itemCount: 1,
  },
  {
    id: "5",
    name: "Product 5",
    stock: 15,
    reviews: { stars: 4, number: 102 },
    price: 199,
    originalPrice: 250,
    image: "/assets/p5.webp",
    itemCount: 1,
  },
  {
    id: "7",
    name: "Product 7",
    stock: 10,
    reviews: { stars: 5, number: 120 },
    price: 649,
    originalPrice: 799,
    image: "/assets/p7.webp",
    itemCount: 1,
  },
  {
    id: "9",
    name: "Product 9",
    stock: 18,
    reviews: { stars: 4, number: 67 },
    price: 379,
    originalPrice: 450,
    image: "/assets/p9.webp",
    itemCount: 1,
  },
];

export const products = [
  {
    id: "1",
    name: "Product 1",
    stock: 8,
    reviews: { stars: 4, number: 55 },
    price: 444,
    originalPrice: 555,
    image: "/assets/p1.webp",
    itemCount: 1,
  },
  {
    id: "2",
    name: "Product 2",
    stock: 8,
    reviews: { stars: 4, number: 55 },
    price: 444,
    originalPrice: 555,
    image: "/assets/p2.webp",
    itemCount: 1,
  },
  {
    id: "3",
    name: "Product 3",
    stock: 12,
    reviews: { stars: 5, number: 89 },
    price: 555,
    originalPrice: 699,
    image: "/assets/p3.webp",
    itemCount: 1,
  },
  {
    id: "4",
    name: "Product 4",
    stock: 6,
    reviews: { stars: 3, number: 42 },
    price: 299,
    originalPrice: 349,
    image: "/assets/p4.webp",
    itemCount: 1,
  },
  {
    id: "5",
    name: "Product 5",
    stock: 15,
    reviews: { stars: 4, number: 102 },
    price: 199,
    originalPrice: 250,
    image: "/assets/p5.webp",
    itemCount: 1,
  },
  {
    id: "6",
    name: "Product 6",
    stock: 20,
    reviews: { stars: 3, number: 77 },
    price: 129,
    originalPrice: 179,
    image: "/assets/p6.webp",
    itemCount: 1,
  },
  {
    id: "7",
    name: "Product 7",
    stock: 10,
    reviews: { stars: 5, number: 120 },
    price: 649,
    originalPrice: 799,
    image: "/assets/p7.webp",
    itemCount: 1,
  },
  {
    id: "8",
    name: "Product 8",
    stock: 4,
    reviews: { stars: 2, number: 35 },
    price: 89,
    originalPrice: 120,
    image: "/assets/p8.webp",
    itemCount: 1,
  },
  {
    id: "9",
    name: "Product 9",
    stock: 18,
    reviews: { stars: 4, number: 67 },
    price: 379,
    originalPrice: 450,
    image: "/assets/p9.webp",
    itemCount: 1,
  },
  {
    id: "10",
    name: "Product 10",
    stock: 5,
    reviews: { stars: 3, number: 55 },
    price: 299,
    originalPrice: 340,
    image: "/assets/p10.webp",
    itemCount: 1,
  },
  {
    id: "11",
    name: "Product 11",
    stock: 9,
    reviews: { stars: 4, number: 90 },
    price: 499,
    originalPrice: 620,
    image: "/assets/p11.webp",
    itemCount: 1,
  },
];
